### ISSUE TITLE
Render thumbnail video inline

### ISSUE THREAD

**Issue by snobu** [snobu/destreamer#42] opened 2020-04-06 17:00 UTC
## Render thumbnail video inline in the console.

This works on the Mac (both inside VSCode and iTerm), needs testing on Windows.

We already have the thumbnail URL (it's in the same payload with the playbackUrl), we just need to fetch the image and render in the console.

```javascript
term.drawImage('.thumbnail.png', { shrink: { width: 50, height: 50 } });
```

Crude implementation in the _tokencache_ branch -

![image](https://user-images.githubusercontent.com/6472374/78584687-455ab000-7841-11ea-8d4e-aa42d9bec3a9.png)

**Comment by lukaarma** [comment] 2020-04-08 15:15
maybe implement this package: https://github.com/sindresorhus/terminal-image

**Comment by lukaarma** [comment] 2020-04-09 11:48
adda6828a6e8797ae6f35554650caf9ddabc6186 implemented the suggested package and now it's working as intended

**Comment by lukaarma** [comment] 2020-04-10 10:57
adda6828a6e8797ae6f35554650caf9ddabc6186 implemented this and it's working, closing this issue

**Closed by lukaarma** 2020-04-10 10:57 UTC
Labels: enhancement
