### ISSUE TITLE
Error when using multiple download with list.txt

### ISSUE THREAD

**Issue by FraH90** [snobu/destreamer#33] opened 2020-04-01 21:41 UTC
So, I've tried the new functionality for downloading a whole bunch of videos from a text file.
I've put the urls in the text file, one url per each line like it says on the instruction of readme.

I launched this:
`node destreamer.js --username MYUSERNAME --outputdirectory "videos" \ --videoUrls list.txt`

(Also tried using the correct escape character for powershell, same result), I get this:

```
Video URLs: [ 'list.txt' ]
Username: MYUSERNAME
Output Directory: videos
Video/Audio Quality: undefined
Using youtube-dl version 2020.03.08
Using ffmpeg version git-2020-03-15-c467328 Copyright (c) 2000-2020 the FFmpeg developers
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to STS login page...
We are logged in.
Got cookie. Consuming cookie...
Calling Microsoft Stream API...
ApiGatewayUri: https://euwe-1.api.microsoftstream.com/api/
ApiGatewayVersion: 1.3-private
Fetching title and HLS URL...
Error when calling Microsoft Stream API: 400 undefined400
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
```

And chromium crash, not even downloading the first video.
It seems an error calling microsoft stream API.. is it a bug?

**Comment by FraH90** [comment] 2020-04-01 21:45
PS, just for being more clear, this is how it looks my list.txt file:

```
https://web.microsoftstream.com/video/************************************
https://web.microsoftstream.com/video/************************************
https://web.microsoftstream.com/video/************************************
https://web.microsoftstream.com/video/************************************
https://web.microsoftstream.com/video/************************************
https://web.microsoftstream.com/video/************************************
https://web.microsoftstream.com/video/************************************
https://web.microsoftstream.com/video/************************************
https://web.microsoftstream.com/video/************************************
https://web.microsoftstream.com/video/************************************
```

**Comment by snobu** [comment] 2020-04-01 21:50
@kylon can you please take a look at this? I believe this feature was introduced by your PR.

**Comment by lukaarma** [comment] 2020-04-02 02:11
Since it's crashing because of an invalid, can you please pull the last version of destreamer and run it again with the verbose (-v) flag?

**Comment by FraH90** [comment] 2020-04-02 08:31
Done, updated and run with -v flag

Command:

**Comment by snobu** [comment] 2020-04-02 09:08
I tried the latest version of the code from the dev branch and it works fine for me if i use a text file.

Are you using an HTTP proxy or something like that? That 400 Bad request doesn't seem to come back from the MS Stream API, seems to come from something in between. The API only speaks JSON, not HTML.

**Comment by kylon** [comment] 2020-04-02 09:10
maybe some gargabe in the file?
please write the program you are using to create the file

**Comment by lukaarma** [comment] 2020-04-02 09:34
@FraH90 I've slightly changed the way we log errors, would you please clone and run again with the same arguments?

**Comment by FraH90** [comment] 2020-04-02 10:42
> I tried the latest version of the code from the dev branch and it works fine for me if i use a text file.
> 
> Are you using an HTTP proxy or something like that? That `400 Bad Request` doesn't seem to come back from the MS Stream API, seems to come from something in between. MS Stream API only speaks JSON, not HTML.

I'm just using windows firewall controlled by windows firewall control, but I've opened connections for chromium and there's no blocking at all in the connection logs, so that's not the problem.



> maybe some gargabe in the file?
> please write the program you are using to create the file

No garbage i guess, I've written in plain text in sublime text.

**Comment by FraH90** [comment] 2020-04-02 10:45
> @FraH90 I've slightly changed the way we log errors, would you please clone and run again with the same arguments?

Ok, this is what I get now
(PS I've just deleted my username and the GUID of the video):


```
Video URLs: [ 'list.txt' ]
Username: MYUSERNAME
Output Directory: videos
Video/Audio Quality: undefined
Using youtube-dl version 2020.03.08
Using ffmpeg version git-2020-03-15-c467328 Copyright (c) 2000-2020 the FFmpeg developers
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to STS login page...
We are logged in.
Page loaded
Calling Microsoft Stream API...


[VERBOSE] ApiGatewayUri: https://euwe-1.api.microsoftstream.com/api/

            ApiGatewayVersion: 1.3-private


ApiGatewayUri: https://euwe-1.api.microsoftstream.com/api/
ApiGatewayVersion: 1.3-private
Fetching title and HLS URL...
Error when calling Microsoft Stream API: 400 undefined400
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>

Exiting...
[VERBOSE]Error: Request failed with status code 400
    at createError (C:\destreamer-dev\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\destreamer-dev\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\destreamer-dev\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  config: {
    url: 'https://euwe-1.api.microsoftstream.com/api/videos/************************************\r?$expand=creator,tokens,status,liveEvent,extensions&api-version=1.3-private',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiJodHRwczovLyoubWljcm9zb2Z0c3RyZWFtLmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzViNDA2YWFiLWExZjEtNGYxMy1hN2FhLWRkNTczZGEzZDMzMi8iLCJpYXQiOjE1ODU4MjM1NDIsIm5iZiI6MTU4NTgyMzU0MiwiZXhwIjoxNTg1ODI3NDQyLCJhY3IiOiIxIiwiYWlvIjoiNDJkZ1lEZ3NvQ0J2bzdlczVIT01ldkpEOW5xVlgzTG1OdnVXcWJ4OStpRGFmVXFPbmdVQSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiJjZjUzZmNlOC1kZWY2LTRhZWItOGQzMC1iMTU4ZTdiMWNmODMiLCJhcHBpZGFjciI6IjIiLCJmYW1pbHlfbmFtZSI6IkNBVEVSSU5BIiwiZ2l2ZW5fbmFtZSI6IkZSQU5DRVNDTyIsImlwYWRkciI6IjE1MS41MC44OC4xMiIsIm5hbWUiOiJDQVRFUklOQSBGUkFOQ0VTQ08iLCJvaWQiOiIzMmFjN2E1Yy1iYzNhLTQ1ZTEtOGVmNi00NWY0MzYwMDgyNjUiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMTk3NDA3NTU5NC0yMjQ4NTg3MTc3LTM0NDQyMzI0MTMtMTA4MDciLCJwdWlkIjoiMTAwMzNGRkY5NjZDRUNGMCIsInNjcCI6ImFjY2Vzc19taWNyb3NvZnRzdHJlYW1fc2VydmljZSIsInN1YiI6Il9RdzNoOGM1Q3VtbXdsSENPQVlIM04wWjNiYVhTSVoxMGdWU1JUdWxTSDQiLCJ0aWQiOiI1YjQwNmFhYi1hMWYxLTRmMTMtYTdhYS1kZDU3M2RhM2QzMzIiLCJ1bmlxdWVfbmFtZSI6ImYuY2F0ZXJpbmFAc3R1ZGVudGkucG9saWJhLml0IiwidXBuIjoiZi5jYXRlcmluYUBzdHVkZW50aS5wb2xpYmEuaXQiLCJ1dGkiOiJmV1g4dWR3eDFVaXU5YnJRTU85QUFBIiwidmVyIjoiMS4wIn0.HlhoBPdKm15exhJ3QRPjmJZPM1YgPQcCjAiobKK86-eK6_oAY4jhpZZvpuFSbjb7MoVC6-pHrS8P0oi3Lscn7OVXYZgnsWHw76Q7uHxDj0XqLePjQlhyX8b8IWtkw3oibtbGtVu4koYbJxWaJN-KYidJqWDcWzNabbst1N4a3qQW4K3I5rvTZotOo1h2oQ55GrcRMl4UKLAgTH7Ns432DJUIl0gD1SxKqiHcu6DeicQQNpU1mrqf0_Gh-5WPJmM-IB3mEboVuQ0gVhr2xHoegRG80caN7bzPMEW4V_OuzUipEIapoTl6TI6_frW88HJp8n1UdC6uFAwQ7LrhQOm2xg',
      'User-Agent': 'axios/0.19.2'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'euwe-1.api.microsoftstream.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'euwe-1.api.microsoftstream.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 2941,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'euwe-1.api.microsoftstream.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'euwe-1.api.microsoftstream.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 2941,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /api/videos/************************************%0D?$expand=creator,tokens,status,liveEvent,extensions&api-version=1.3-private HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiJodHRwczovLyoubWljcm9zb2Z0c3RyZWFtLmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzViNDA2YWFiLWExZjEtNGYxMy1hN2FhLWRkNTczZGEzZDMzMi8iLCJpYXQiOjE1ODU4MjM1NDIsIm5iZiI6MTU4NTgyMzU0MiwiZXhwIjoxNTg1ODI3NDQyLCJhY3IiOiIxIiwiYWlvIjoiNDJkZ1lEZ3NvQ0J2bzdlczVIT01ldkpEOW5xVlgzTG1OdnVXcWJ4OStpRGFmVXFPbmdVQSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiJjZjUzZmNlOC1kZWY2LTRhZWItOGQzMC1iMTU4ZTdiMWNmODMiLCJhcHBpZGFjciI6IjIiLCJmYW1pbHlfbmFtZSI6IkNBVEVSSU5BIiwiZ2l2ZW5fbmFtZSI6IkZSQU5DRVNDTyIsImlwYWRkciI6IjE1MS41MC44OC4xMiIsIm5hbWUiOiJDQVRFUklOQSBGUkFOQ0VTQ08iLCJvaWQiOiIzMmFjN2E1Yy1iYzNhLTQ1ZTEtOGVmNi00NWY0MzYwMDgyNjUiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMTk3NDA3NTU5NC0yMjQ4NTg3MTc3LTM0NDQyMzI0MTMtMTA4MDciLCJwdWlkIjoiMTAwMzNGRkY5NjZDRUNGMCIsInNjcCI6ImFjY2Vzc19taWNyb3NvZnRzdHJlYW1fc2VydmljZSIsInN1YiI6Il9RdzNoOGM1Q3VtbXdsSENPQVlIM04wWjNiYVhTSVoxMGdWU1JUdWxTSDQiLCJ0aWQiOiI1YjQwNmFhYi1hMWYxLTRmMTMtYTdhYS1kZDU3M2RhM2QzMzIiLCJ1bmlxdWVfbmFtZSI6ImYuY2F0ZXJpbmFAc3R1ZGVudGkucG9saWJhLml0IiwidXBuIjoiZi5jYXRlcmluYUBzdHVkZW50aS5wb2xpYmEuaXQiLCJ1dGkiOiJmV1g4dWR3eDFVaXU5YnJRTU85QUFBIiwidmVyIjoiMS4wIn0.HlhoBPdKm15exhJ3QRPjmJZPM1YgPQcCjAiobKK86-eK6_oAY4jhpZZvpuFSbjb7MoVC6-pHrS8P0oi3Lscn7OVXYZgnsWHw76Q7uHxDj0XqLePjQlhyX8b8IWtkw3oibtbGtVu4koYbJxWaJN-KYidJqWDcWzNabbst1N4a3qQW4K3I5rvTZotOo1h2oQ55GrcRMl4UKLAgTH7Ns432DJUIl0gD1SxKqiHcu6DeicQQNpU1mrqf0_Gh-5WPJmM-IB3mEboVuQ0gVhr2xHoegRG80caN7bzPMEW4V_OuzUipEIapoTl6TI6_frW88HJp8n1UdC6uFAwQ7LrhQOm2xg\r\n' +
      'User-Agent: axios/0.19.2\r\n' +
      'Host: euwe-1.api.microsoftstream.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    insecureHTTPParser: undefined,
    path: '/api/videos/************************************%0D?$expand=creator,tokens,status,liveEvent,extensions&api-version=1.3-private',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      connection: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular],
      responseUrl: 'https://euwe-1.api.microsoftstream.com/api/videos/************************************%0D?$expand=creator,tokens,status,liveEvent,extensions&api-version=1.3-private',
      redirects: [],
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'https://euwe-1.api.microsoftstream.com/api/videos/************************************%0D?$expand=creator,tokens,status,liveEvent,extensions&api-version=1.3-private',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      authorization: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      'content-type': 'text/html; charset=us-ascii',
      server: 'Microsoft-HTTPAPI/2.0',
      date: 'Thu, 02 Apr 2020 10:37:29 GMT',
      connection: 'close',
      'content-length': '324'
    },
    config: {
      url: 'https://euwe-1.api.microsoftstream.com/api/videos/************************************\r?$expand=creator,tokens,status,liveEvent,extensions&api-version=1.3-private',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /api/videos/************************************%0D?$expand=creator,tokens,status,liveEvent,extensions&api-version=1.3-private HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiJodHRwczovLyoubWljcm9zb2Z0c3RyZWFtLmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzViNDA2YWFiLWExZjEtNGYxMy1hN2FhLWRkNTczZGEzZDMzMi8iLCJpYXQiOjE1ODU4MjM1NDIsIm5iZiI6MTU4NTgyMzU0MiwiZXhwIjoxNTg1ODI3NDQyLCJhY3IiOiIxIiwiYWlvIjoiNDJkZ1lEZ3NvQ0J2bzdlczVIT01ldkpEOW5xVlgzTG1OdnVXcWJ4OStpRGFmVXFPbmdVQSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiJjZjUzZmNlOC1kZWY2LTRhZWItOGQzMC1iMTU4ZTdiMWNmODMiLCJhcHBpZGFjciI6IjIiLCJmYW1pbHlfbmFtZSI6IkNBVEVSSU5BIiwiZ2l2ZW5fbmFtZSI6IkZSQU5DRVNDTyIsImlwYWRkciI6IjE1MS41MC44OC4xMiIsIm5hbWUiOiJDQVRFUklOQSBGUkFOQ0VTQ08iLCJvaWQiOiIzMmFjN2E1Yy1iYzNhLTQ1ZTEtOGVmNi00NWY0MzYwMDgyNjUiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMTk3NDA3NTU5NC0yMjQ4NTg3MTc3LTM0NDQyMzI0MTMtMTA4MDciLCJwdWlkIjoiMTAwMzNGRkY5NjZDRUNGMCIsInNjcCI6ImFjY2Vzc19taWNyb3NvZnRzdHJlYW1fc2VydmljZSIsInN1YiI6Il9RdzNoOGM1Q3VtbXdsSENPQVlIM04wWjNiYVhTSVoxMGdWU1JUdWxTSDQiLCJ0aWQiOiI1YjQwNmFhYi1hMWYxLTRmMTMtYTdhYS1kZDU3M2RhM2QzMzIiLCJ1bmlxdWVfbmFtZSI6ImYuY2F0ZXJpbmFAc3R1ZGVudGkucG9saWJhLml0IiwidXBuIjoiZi5jYXRlcmluYUBzdHVkZW50aS5wb2xpYmEuaXQiLCJ1dGkiOiJmV1g4dWR3eDFVaXU5YnJRTU85QUFBIiwidmVyIjoiMS4wIn0.HlhoBPdKm15exhJ3QRPjmJZPM1YgPQcCjAiobKK86-eK6_oAY4jhpZZvpuFSbjb7MoVC6-pHrS8P0oi3Lscn7OVXYZgnsWHw76Q7uHxDj0XqLePjQlhyX8b8IWtkw3oibtbGtVu4koYbJxWaJN-KYidJqWDcWzNabbst1N4a3qQW4K3I5rvTZotOo1h2oQ55GrcRMl4UKLAgTH7Ns432DJUIl0gD1SxKqiHcu6DeicQQNpU1mrqf0_Gh-5WPJmM-IB3mEboVuQ0gVhr2xHoegRG80caN7bzPMEW4V_OuzUipEIapoTl6TI6_frW88HJp8n1UdC6uFAwQ7LrhQOm2xg\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Host: euwe-1.api.microsoftstream.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/videos/************************************%0D?$expand=creator,tokens,status,liveEvent,extensions&api-version=1.3-private',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">\r\n' +
      '<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n' +
      '<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>\r\n' +
      '<BODY><h2>Bad Request - Invalid URL</h2>\r\n' +
      '<hr><p>HTTP Error 400. The request URL is invalid.</p>\r\n' +
      '</BODY></HTML>\r\n'
  },
  isAxiosError: true,
  toJSON: [Function]
}
```

**Comment by lukaarma** [comment] 2020-04-02 10:54
Found the error, the carriage return is not stripped from the url when is read from the file.

you can see it here

> `url: 'https://euwe-1.api.microsoftstream.com/api/videos/************************************\r?$expand=creator,tokens,status,liveEvent,extensions&api-version=1.3-private',`

the \r after the video-ID

maybe @kylon could take a look if he wants?

**Comment by kylon** [comment] 2020-04-02 10:59
yeah, working on it, i ll push the changes when my lesson ends

**Comment by snobu** [comment] 2020-04-02 16:15
Git pull, build and try again. @kylon introduced a fix that should correctly split text files on Windows as well (`\r\n` terminated).

**Comment by FraH90** [comment] 2020-04-03 11:33
> Git pull, build and try again. @kylon introduced a fix that should correctly split text files on Windows as well (`\r\n` terminated). Thanks to everyone involved in reporting and fixing this.

Guys.. I'm sorry to re-open this issue again.. but it seems it's not really fixed on win.

Today, I've updated destreamer to the latest version, I've build, and then launched this:

```
node destreamer.js --username MYUSERNAME --outputdirectory "videos" \ --videoUrls list.txt
```

It downloaded correctly the first video, then at the time of downloading the second video of the list it crashed down and gave me that:

```
size=   49880kB time=00:52:35.22 bitrate= 129.5kbits/s speed=12.4x
video:0kB audio:49301kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.174640%
[ffmpeg] Downloaded 51076886 bytes
[download] 100% of 48.71MiB in 04:15
[ffmpeg] Merging formats into "videos\NAMEOFTHEVIDEO.mp4"
Deleting original file videos\NAMEOFTHEVIDEO.f569.mp4 (pass -k to keep)
Deleting original file videos\NAMEOFTHEVIDEO.f137.mp4 (pass -k to keep)
Unhandled error!
Timeout or fatal error, please check your downloads and try again if necessary.
Error: Protocol error (Page.navigate): Cannot navigate to invalid URLC:\destreamer-dev\destreamer.js:239
    throw new Error("Killing process..\n");
    ^

Error: Killing process..

    at process.<anonymous> (C:\destreamer-dev\destreamer.js:239:11)
    at process.emit (events.js:311:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

I'm doing it again now, running it with verbose mode on so I can get more details on the error.
I'll keep u updated

**Comment by kylon** [comment] 2020-04-03 11:45
i suppose it could be an empty line this time, the next PR will address this
probably added by sublime

**Comment by FraH90** [comment] 2020-04-03 11:46
> > Git pull, build and try again. @kylon introduced a fix that should correctly split text files on Windows as well (`\r\n` terminated). Thanks to everyone involved in reporting and fixing this.
> 
> Guys.. I'm sorry to re-open this issue again.. but it seems it's not really fixed on win.
> 
> Today, I've updated destreamer to the latest version, I've build, and then launched this:
> 
> ```
> node destreamer.js --username MYUSERNAME --outputdirectory "videos" \ --videoUrls list.txt
> ```
> 
> It downloaded correctly the first video, then at the time of downloading the second video of the list it crashed down and gave me that:
> 
> ```
> size=   49880kB time=00:52:35.22 bitrate= 129.5kbits/s speed=12.4x
> video:0kB audio:49301kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.174640%
> [ffmpeg] Downloaded 51076886 bytes
> [download] 100% of 48.71MiB in 04:15
> [ffmpeg] Merging formats into "videos\NAMEOFTHEVIDEO.mp4"
> Deleting original file videos\NAMEOFTHEVIDEO.f569.mp4 (pass -k to keep)
> Deleting original file videos\NAMEOFTHEVIDEO.f137.mp4 (pass -k to keep)
> Unhandled error!
> Timeout or fatal error, please check your downloads and try again if necessary.
> Error: Protocol error (Page.navigate): Cannot navigate to invalid URLC:\destreamer-dev\destreamer.js:239
>     throw new Error("Killing process..\n");
>     ^
> 
> Error: Killing process..
> 
>     at process.<anonymous> (C:\destreamer-dev\destreamer.js:239:11)
>     at process.emit (events.js:311:20)
>     at processPromiseRejections (internal/process/promises.js:209:33)
>     at processTicksAndRejections (internal/process/task_queues.js:98:32)
> ```
> 
> I'm doing it again now, running it with verbose mode on so I can get more details on the error.
> I'll keep u updated

So, sadly verbose doesn't add any info on the error ;(
It just gives me that again:

```
[ffmpeg] Merging formats into "videos\NAMEOFTHEVIDEO.mp4"
Deleting original file videos\NAMEOFTHEVIDEO.f513.mp4 (pass -k to keep)
Deleting original file videos\NAMEOFTHEVIDEO.f137.mp4 (pass -k to keep)
Unhandled error!
Timeout or fatal error, please check your downloads and try again if necessary.
Error: Protocol error (Page.navigate): Cannot navigate to invalid URLC:\destreamer-dev\destreamer.js:239
    throw new Error("Killing process..\n");
    ^

Error: Killing process..

    at process.<anonymous> (C:\destreamer-dev\destreamer.js:239:11)
    at process.emit (events.js:311:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

**Comment by FraH90** [comment] 2020-04-03 11:48
> i suppose it could be an empty line this time, the next PR will address this
> probably added by sublime

Mmh. Don't know.
Opening it with any plain text editor I don't see any empty line.

**Comment by kylon** [comment] 2020-04-03 12:05
try this, replace and rebuild.

just run: node destreamer.js -V yourfile.txt -s -v
kill the process when chrome runs and look for _[VERBOSE] URL list_


[destreamer.ts.zip](https://github.com/snobu/destreamer/files/4427050/destreamer.ts.zip)

**Comment by FraH90** [comment] 2020-04-03 12:33
> try this, replace and rebuild.
> 
> just run: node destreamer.js -V yourfile.txt -s -v
> kill the process when chrome runs and look for _[VERBOSE] URL list_ in your terminal
> 
> [destreamer.ts.zip](https://github.com/snobu/destreamer/files/4427050/destreamer.ts.zip)

Ok, think you were right, this is what I get:

```
Video URLs: [ 'list.txt' ]
Username: undefined
There will be no video downloaded, it's only a simulation
Using youtube-dl version 2020.03.08
Using ffmpeg version git-2020-03-15-c467328 Copyright (c) 2000-2020 the FFmpeg developers
[VERBOSE] URL List:
[
  'https://web.microsoftstream.com/video/60**********************************',
  'https://',
  'https://web.microsoftstream.com/video/6c**********************************',
  'https://',
  'https://web.microsoftstream.com/video/15**********************************',
  'https://',
  'https://web.microsoftstream.com/video/a8**********************************'
]
```

It seems that for some reason it inserts in the array an empty line with just "https://", even if this is not present in my text file.

**Comment by kylon** [comment] 2020-04-03 12:47
same as above but you should see a proper url list now

[destreamer.ts.zip](https://github.com/snobu/destreamer/files/4427248/destreamer.ts.zip)

**Comment by snobu** [comment] 2020-04-03 13:03
Ok @kylon, your PR your problem :)

**Comment by FraH90** [comment] 2020-04-03 13:11
> same as above but you should see a proper url list now
> 
> [destreamer.ts.zip](https://github.com/snobu/destreamer/files/4427248/destreamer.ts.zip)

Ok done, guess now you've fixed it, seems clean

```
PS C:\destreamer-dev> node destreamer.js -V list.txt -s -v
Video URLs: [ 'list.txt' ]
Username: undefined
There will be no video downloaded, it's only a simulation
Using youtube-dl version 2020.03.08
Using ffmpeg version git-2020-03-15-c467328 Copyright (c) 2000-2020 the FFmpeg developers
[VERBOSE] URL List:
[
  'https://web.microsoftstream.com/video/60f329c0-12b1-4ef8-8eff-af9fc24f415d',
  'https://web.microsoftstream.com/video/6ca00d8b-3f4e-484d-885a-1d876f600231',
  'https://web.microsoftstream.com/video/15f796c7-6ee5-4805-81c1-0ec4f1312dd3',
  'https://web.microsoftstream.com/video/a8dcd377-e15a-47fa-8bac-edf621f2e481'
]
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to STS login page...
```

**Comment by snobu** [comment] 2020-04-03 13:21
@kylon, could you please add a unit test for the file parsing? You can rename BrowserTests.ts to Tests.ts and add it in there. This way we won't have regressions later on if/when we change parsing.

**Comment by snobu** [comment] 2020-04-04 20:42
Fixed in https://github.com/snobu/destreamer/commit/f01ef06b6ac557b70060d34b778bc7dcb8a1c98c. Unit tests added. All credit to @kylon. Thanks!

**Closed by snobu** 2020-04-04 20:42 UTC
Labels: bug
