### ISSUE TITLE
Saving video when network disconnects ...

### ISSUE THREAD

**Issue by chiragdkothari** [snobu/destreamer#120] opened 2020-05-05 14:33 UTC
hello, 
forgot to mention in the last issue , but really appreciate Destreamer and has saved a lot of time and energy for me .... 
one thing i noticed was while downloading a video, if the network disconnects the progress jumps to 100% in the console and the video is saved with whatever was downloaded before disconnecting and the console displays the video is downloaded and no error message is displayed.... 
i tried using the -v but not information was displayed in the console ....

**Comment by snobu** [comment] 2020-05-05 14:49
Thanks for reporting this. Will look into it.

**Comment by chiragdkothari** [comment] 2020-05-05 19:31
also the new version is lot more CPU intensive than the previous one ... is it supposed to be lite that?

**Comment by lukaarma** [comment] 2020-05-05 19:40
With new version what do you mean? 2.0 or the aria2c branch?

**Comment by chiragdkothari** [comment] 2020-05-05 20:01
2.0

**Comment by snobu** [comment] 2020-05-05 20:17
Are you getting .mkv files as output? If you're getting mp4, do a git pull as we just merged a PR that fixes the re-encoding problem (you now get exactly what MS Stream has in terms of codec and bitrate).

**Comment by chiragdkothari** [comment] 2020-05-05 20:34
oh ok .... i am using the forked one which is optimised for polimi ....

**Comment by snobu** [comment] 2020-05-05 20:58
Use our project instead and copy over the password filling logic from the Polimi fork. Should be easy it's just the few lines after puppeteer auto fills the username.

**Comment by chiragdkothari** [comment] 2020-05-05 21:31
ok thanks...

**Comment by snobu** [comment] 2020-05-18 18:13
I am able to reproduce this by switching on Airplane mode mid-download. We need to check if the `error` event is raised, but it's probably not, else we would not have a partial download.

**Comment by lukaarma** [comment] 2020-07-23 14:02
@snobu can I close this? I was not able to reproduce even using Airplane mode and is such a rare occurrence that we can safely ignore it, no?

**Comment by snobu** [comment] 2020-07-23 20:11
Strange. I am able to consistently repro this bug. I kick off a download, 5% or so in i tap on Airplane Mode, progress bar goes to 100% and the download finishes with error code 0, so nobody raises any error event.

![image](https://user-images.githubusercontent.com/6472374/88334014-c7f87400-cd39-11ea-9aca-88eb3119168e.png)

What happens in your case?

**Comment by lukaarma** [comment] 2020-07-23 20:59
I get an `Unknown FFmpeg error` but if i disconnect my router mid-download I get the same behaviour as you do!

I say we can safely ignore this until I finish working on the aria2c branch when it wont be a problem anymore

**Comment by snobu** [comment] 2020-07-23 21:14
Agreed.

**Closed by snobu** 2020-07-23 21:14 UTC
Labels: bug
