### ISSUE TITLE
aria2.onDownloadError

### ISSUE THREAD

**Issue by Alex87a** [snobu/destreamer#256] opened 2020-10-12 18:24 UTC
[ERROR] {"jsonrpc":"2.0","method":"aria2.onDownloadError","params":[{"gid":"8cebe1d32bd00ded"}]}

[ERROR] RECIVED URL TO RETRY, NOT IMPLEMENTED YET

[ERROR] {
    "id": "getUrlForRetry",
    "jsonrpc": "2.0",
    "error": {
        "code": 1,
        "message": "The parameter at 0 has wrong type."
    }
}

**Comment by lukaarma** [comment] 2020-10-12 18:43
Duplicate of #249

**Closed by lukaarma** 2020-10-12 18:43 UTC
Labels: duplicate
