### ISSUE TITLE
destreamer.js missing

### ISSUE THREAD

**Issue by lgm-pyles** [snobu/destreamer#108] opened 2020-04-28 22:23 UTC
Hello!

Same as Aknabacus (Module missing destreamer.js #85  closed issue), I cannot find:
build\src\destreamer.js             in my destreamer folder
(and for a blink second I have an error message similar to Aknabacus's one) 

but I did create a file .cmd containing:
git clone https://github.com/snobu/destreamer
cd destreamer
npm install
npm run build
    (as was suggested to Aknabacus)

and I do have:   Node.js, npm, ffmpeg (in the same directory as README) and git
and now a "destreamer" folder with the following folders:   .github, .vscode, assets, ffmpeg..., node_modules, scripts, src, test

But I haven't any "build" folder 

So, what is it I did wrong?

**Comment by kylon** [comment] 2020-04-28 22:31
paste the error

**Comment by lgm-pyles** [comment] 2020-04-29 07:17
When I try to open destreamer.cmd, this is what appears for a split second:

___
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'C:\Users\Lea\Desktop\Covid\sos\destreamers\build\src\destreamer.js'
�[90m   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)�[39m
�[90m   at Function.Module._load (internal/modules/cjs/loader.js:840:27)�[39m
�[90m   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)�[39m
�[90m   at internal/main/run_main_module.js:18:47�[39m {
code: �[32m'MODULE_NOT_FOUND'�[39m,
requireStack: []
}
___

This has not been pasted because the window disapears immediatly: I wrote it from a printscreen

**Comment by lukaarma** [comment] 2020-04-29 07:55
I think you didn't build destreamer using the instructions in the reasons.md

**Comment by snobu** [comment] 2020-04-29 08:04
`cd` to your destreamer folder with
```
cd destreamer
```
then install dependencies and build -
```
npm install
npm run build
```

That's it, now you can follow the README for usage.

**Comment by lgm-pyles** [comment] 2020-04-29 14:44
Thanks to all your advice, "Destreamer was built successfully"
It was actually very simple but I lacked basics, so it's been a long journey...
Thank you Kylon, Lukaarma and Snobu

**Comment by lukaarma** [comment] 2020-04-29 14:53
No problems!
If it's all working and downloading as intended please go ahead and close the issue, otherwise we are happy to help you

**Comment by lgm-pyles** [comment] 2020-04-29 20:15
It's working (despite many wanderings) but it starts again once the download has been completed with a new video entitled "[video_name] - 1", which is not really a problem (I just have to close the command prompt and delete the new file)

Is there a way to fix that?

**Comment by lukaarma** [comment] 2020-04-29 20:18
Did you feed Destreamer more than one link?
If not can you please run it with the verbose flag and paste back here the output (take care of censoring your personal info)

**Comment by gelmanovic** [comment] 2020-04-29 20:32
> It's working (despite many wanderings) but it starts again once the download has been completed with a new video entitled "[video_name] - 1", which is not really a problem (I just have to close the command prompt and delete the new file)
> 
> Is there a way to fix that?

That happens to me when i download multiple videos with the same title, this last aspect being due to default file name generation of teams recordings.

**Comment by lgm-pyles** [comment] 2020-04-29 21:20
(c) 2019 Microsoft Corporation. Tutti i diritti sono riservati.

C:\Windows\System32>cd C:\Users\Lea\Desktop\Equipe\sos\destreamer

C:\Users\Lea\Desktop\Equipe\sos\destreamer>destreamer.cmd -i https://web.microsoftstream.com/video/VIDEO-1 --verbose
Using ffmpeg version git-2020-04-29-280383a Copyright (c) 2000-2020 the FFmpeg developers

Video URLs:
[
  'https://web.microsoftstream.com/video/VIDEO-1'
]

Access token has expired.
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
We are logged in.
Wrote access token to token cache.
At this point Chromium's job is done, shutting it down...

Fresh access token dropped into .token_cache
Video GUIDs:
[ 'VIDEO-1' ]
Fetching metadata...
Calling https://euwe-1.api.microsoftstream.com/api/videos/VIDEO-1?api-version=1.4-private
[ 'videos' ]

Downloading Video: Riunione in "Generale"

▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
(...)
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

Spawning ffmpeg with access token and HLS URL. This may take a few seconds...
Using a fresh cookie.
progress [████████████████████████████████████████] 100% 197.0kbits/s 0s

Download finished: videos\Riunione in Generale - 16-04-2020.mp4
Using ffmpeg version git-2020-04-29-280383a Copyright (c) 2000-2020 the FFmpeg developers

Video URLs:
[
  'https://web.microsoftstream.com/video/VIDEO-1'
]

Access token still good for 59 minutes.

Video GUIDs:
[ 'VIDEO-1' ]
Fetching metadata...
Calling https://euwe-1.api.microsoftstream.com/api/videos/VIDEO-1?api-version=1.4-private
[ 'videos' ]

Downloading Video: Riunione in "Generale"

▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
(...)
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

Spawning ffmpeg with access token and HLS URL. This may take a few seconds...
Using a fresh cookie.
progress [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% 0 0s

ffmpeg returned an error: https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://o5wonsl3ikd5uf2s3qeavxkf4d-euwe.streaming.media.azure.net/c750e57b-488f-4a70-840c-9cdad272d592/1-5uzexnjuqyxqrzmo2qxxv7ngoc.ism/manifest(format=m3u8-aapl): Invalid data found when processing input



Unknown FFmpeg error

C:\Users\Lea\Desktop\Equipe\sos\destreamer>

**Comment by lukaarma** [comment] 2020-04-29 21:25
Ok thanks it's the same as #111, closing this one and moving the discussion there

**Comment by lgm-pyles** [comment] 2020-04-29 21:26
thanks

**Closed by lukaarma** 2020-04-29 21:25 UTC
Labels: question

**Comment by snobu** [comment] 2020-04-30 21:52
Fixed via https://github.com/snobu/destreamer/commit/0f7f585debab86d544813887f8daa99e789cda3c

`git pull` to get the new (fixed) cmd script.
